Adapter setting
holgerhagen/taskana-doc pull request #40
Opened 2024-05-31 12:40 UTC by jamesrdi

2024-06-04 08:43 UTC, ryzheboka requested changes

2024-06-04 08:43 UTC, ryzheboka commented on docs/user-guide/adapter/gettingStarted.md
> +- Working TASKANA application (see [here](../getting-started/exampleSpringBoot.md) for instructions)
Postgres or Docker (for running postgres) is another requirement here

2024-06-04 08:43 UTC, ryzheboka commented on docs/user-guide/adapter/gettingStarted.md
> +<dependency>
This pom segment is not formatted correctly

2024-06-04 08:43 UTC, ryzheboka commented on docs/user-guide/adapter/gettingStarted.md
> +<repositories>
This pom segment is also not formatted correctly

2024-06-04 08:43 UTC, ryzheboka commented on docs/user-guide/adapter/gettingStarted.md
> +If you are not using application.yaml, delete it and add the following file to your resources folder:
This needs to be written differently. The important information is that you need to use either application.properties or application.yaml. In most cases, you don't need to delete one of them

2024-06-04 08:43 UTC, ryzheboka commented on docs/user-guide/adapter/gettingStarted.md
> +![Local Image](../static/adapter/adapter-initialization.png)
In this screenshot, Spring-Boot 3.1 is not supported anymore. Can you adjust the whole guide to use Spring Boot 3.2 and test it?

2024-06-04 08:43 UTC, ryzheboka commented on docs/user-guide/adapter/gettingStarted.md
> +
Before step 2, the changed Camunda application needs to be started to see that it still runs correctly

2024-06-04 08:43 UTC, ryzheboka commented on docs/user-guide/adapter/gettingStarted.md
> +<dependencies>
This pom segment is not formatted correctly

2024-06-04 08:43 UTC, ryzheboka commented on docs/user-guide/adapter/gettingStarted.md
> +```
This will require additional imports. Please add this information

2024-06-04 08:43 UTC, ryzheboka commented on docs/user-guide/adapter/gettingStarted.md
> +First, check if your postgres database is running. For example, start the container provided in the TASKANA repository using "bash ./docker-databases/prepare_db.sh POSTGRES_14 && exit".
Please format the bash command as code and make clear that you need to use it in a terminal

2024-06-04 08:43 UTC, ryzheboka commented on docs/user-guide/adapter/gettingStarted.md
> +1. Start a process with a User Task in Camunda. Open tasklist to see the Camunda Task there. The User Task should be imported to TASKANA automatically. You can check it by making a postgres GET reque
You don't need to specify opening tasklist.

2024-06-04 08:43 UTC, ryzheboka commented on docs/user-guide/adapter/gettingStarted.md
> +1. Start a process with a User Task in Camunda. Open tasklist to see the Camunda Task there. The User Task should be imported to TASKANA automatically. You can check it by making a postgres GET reque
There is no request after "following request"

2024-06-04 08:43 UTC, ryzheboka commented on docs/user-guide/adapter/gettingStarted.md
> +1. Start a process with a User Task in Camunda. Open tasklist to see the Camunda Task there. The User Task should be imported to TASKANA automatically. You can check it by making a postgres GET reque
Add, that the user needs to make sure to use the correct port for the TASKANA request. Then, add where you can find the port

2024-06-04 08:43 UTC, ryzheboka commented on docs/user-guide/adapter/gettingStarted.md
> +   GET http://localhost:8080/taskana/api/v1/tasks?name-like=Say hello
How will the user have a Task with the name "Say Hello"? Please add this to the instructions

2024-06-04 08:43 UTC, ryzheboka commented on docs/user-guide/adapter/gettingStarted.md
> +   It should look like this in the Camunda UI:
We don't need to specify how it looks in the Camunda UI. It should suffice to tell the user that he can see that the Camunda Task is claimed

2024-06-04 08:43 UTC, ryzheboka commented on docs/user-guide/adapter/gettingStarted.md
> +   It should look like this in the Camunda UI:
We don't need to specify how it looks in the Camunda UI. It should suffice to tell the user that he can see that the Camunda Task is completed

2024-06-05 10:52 UTC, jamesrdi commented on docs/user-guide/adapter/gettingStarted.md
> +![Local Image](../static/adapter/adapter-initialization.png)
Yes, I have changed the spring boot dependencies to 3.2 and the taskana adapter version to 3.1.0 and tested them together with Taskana version 8.1.0, and it worked

2024-06-07 09:25 UTC, ryzheboka requested changes

2024-06-07 09:25 UTC, ryzheboka commented on docs/user-guide/adapter/gettingStarted.md
> +- Postgres or Docker (for running postgres)
Can you reword "for running postgres"?

2024-06-07 09:25 UTC, ryzheboka commented on docs/user-guide/adapter/gettingStarted.md
> +<dependency>
It is still not formatted correctly

2024-06-07 09:25 UTC, ryzheboka commented on docs/user-guide/adapter/gettingStarted.md
> +
Add that the user can close the Camunda application after checking that it runs correctly

2024-06-07 09:25 UTC, ryzheboka commented on docs/user-guide/adapter/_category_.json
> +  "position": 2,
Can you move it to the bottom instead of second place?

2024-06-07 09:25 UTC, ryzheboka commented on docs/user-guide/adapter/gettingStarted.md
> +   This will filter out names that are not like "Say hello" and give us the user task in TASKANA. Here we assume that the name of the user task is "Say hello to demo", but you can set the name differ
Why do you assume that the name is "Say Hello"? Can you explain that the user needs to enter the name of the Task from the process before giving the REST call?

2024-06-07 09:25 UTC, ryzheboka commented on docs/user-guide/adapter/gettingStarted.md
> +   This will filter out names that are not like "Say hello" and give us the user task in TASKANA. Here we assume that the name of the user task is "Say hello to demo", but you can set the name differ
You don't need the " This will filter out names that are not like "Say hello" and give us the user task in TASKANA."

2024-06-07 10:46 UTC, jamesrdi commented on docs/user-guide/adapter/gettingStarted.md
> +- Postgres or Docker (for running postgres)
How about "to set up postgres database"

2024-07-09 08:44 UTC, ryzheboka approved these changes

2024-07-09 08:44 UTC, merged